### ISSUE TITLE
The result of running the python code is empty

### ISSUE THREAD

**Issue by LUT-NLP** [Mooon/Online_data_driven_control#1]
Hello, sorry to bother you. I want to ask if the code in this code base is complete. The result of running the python code I tried is empty.

**Comment by Mooon** [comment]
It seems that the result might be empty depending the feasibility and solution of the CVXPY problem. CVXPY is less robust to SDP constraints respect to CVX in Matlab, which can lead to infeasibility or suboptimal solutions. 
For example, In Python, `K = np.linalg.solve(P.value, U0 @ Q.value)` requires `P.value` to be invertible. If `P.value` is close to singular or non-invertible, `np.linalg.solve` will fail.  Therefore the empty result.
Switching to different solver (such as MOSEK?) might lead to better results. 

Besides the solver, there could be some workaround to make the python script work more similar to matlab. 
- ensure P.value is invertible before calculating K:
```
if P.value is not None and np.linalg.cond(P.value) < 1 / np.finfo(P.value.dtype).eps:
    K = np.linalg.solve(P.value, U0 @ Q.value)
else:
    K = old_K
    print("Using old K due to singular or undefined P")
```
- regarding numerical stability of the code, you might need to add regularization:
`P = cp.Variable((n, n), symmetric=True) + 1e-5 * np.eye(n)`
- you could also check the convergence status of the solve by printing out `prob.status` to ensure that the optimization problem is feasible.

Let me know whether these steps are helpful.

**Comment by LUT-NLP** [comment]
Hello, I ran it successfully. There was something wrong with my previous operation. Now I can run it normally and get two pictures.
